### ISSUE TITLE
Add eslint and prettier-eslint

### ISSUE THREAD

**Issue by thamaraiselvam** [thamaraiselvam/HackerRank#10]

**Comment by joevo2** [comment]
i would like to work on this is it ok? can you assign it to me?

**Comment by thamaraiselvam** [comment]
Appreciated your interest @joevo2, I have assigned you. Please start working on it

**Comment by joevo2** [comment]
would you like just a config file or you would like it to have eslint/prettier on devDependencies and script to run it?

**Comment by thamaraiselvam** [comment]
there should be script to run it so we can add it into Travis CI.

**Comment by thamaraiselvam** [comment]
@joevo2 still working on it?

**Comment by joevo2** [comment]
@thamaraiselvam sorry about that.

**Comment by thamaraiselvam** [comment]
@sandhyak-tech  if you are interested, can you also pickup https://github.com/thamaraiselvam/HackerRank/issues/38

**Comment by thamaraiselvam** [comment]
Fixed https://github.com/thamaraiselvam/HackerRank/pull/37 
Appreciate your effort @sandhyak-tech
